name: safekey_flutter
description: App Flutter com Firebase Auth, Firestore e gerador de senhas por API.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.4
  shared_preferences: ^2.2.3
  lottie: ^3.1.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/splash.json
    - assets/lottie/intro1.json
    - assets/lottie/intro2.json
    - assets/lottie/intro3.json
    - assets/images/logo.png
    - assets/images/empty_state.png
    - assets/lottie/premium.json
