// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDv-siRyN23ffVP-i0X1aDDdFIGe6qsBY',
    appId: '1:164909988157:web:38b7003cc5408c073bad54',
    messagingSenderId: '164909988157',
    projectId: 'safekey-felipe-001',
    authDomain: 'safekey-felipe-001.firebaseapp.com',
    storageBucket: 'safekey-felipe-001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-IjjPN6XxeRe8yttf9Ai68mthSiQmdz8',
    appId: '1:164909988157:android:161c9cd93cb839833bad54',
    messagingSenderId: '164909988157',
    projectId: 'safekey-felipe-001',
    storageBucket: 'safekey-felipe-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyKbHCJgYidIekY7gYnsqEoM9wPIbgpTk',
    appId: '1:164909988157:ios:7c44e46e8707b88e3bad54',
    messagingSenderId: '164909988157',
    projectId: 'safekey-felipe-001',
    storageBucket: 'safekey-felipe-001.firebasestorage.app',
    iosClientId: '164909988157-62opv11l6lc0a6fang1mj42ulbpp7jmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.safekeyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyKbHCJgYidIekY7gYnsqEoM9wPIbgpTk',
    appId: '1:164909988157:ios:7c44e46e8707b88e3bad54',
    messagingSenderId: '164909988157',
    projectId: 'safekey-felipe-001',
    storageBucket: 'safekey-felipe-001.firebasestorage.app',
    iosClientId: '164909988157-62opv11l6lc0a6fang1mj42ulbpp7jmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.safekeyFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDv-siRyN23ffVP-i0X1aDDdFIGe6qsBY',
    appId: '1:164909988157:web:f15cbd7c2a268eae3bad54',
    messagingSenderId: '164909988157',
    projectId: 'safekey-felipe-001',
    authDomain: 'safekey-felipe-001.firebaseapp.com',
    storageBucket: 'safekey-felipe-001.firebasestorage.app',
  );
}
